### ISSUE TITLE
Quilt 0.27.1 

### ISSUE THREAD

**Issue by Seltyk** [Infinidoge/nix-minecraft#111]
The install phase of mkTextileLoader [deletes META-INF files](https://github.com/Infinidoge/nix-minecraft/blob/a950aa08f1868355d8b5fe89613f17468d2ae697/pkgs/build-support/mkTextileLoader.nix#L55). In the latest Quilt beta, these files are not present in the JAR, and the zip command exits non-zero (code 12, specifically). I suspect this is not a fatal error, but the Nix build fails here anyway.

**Comment by Infinidoge** [comment]
I need to setup proper CI for the actual packages and not just the update script, that could have caught this. Good catch.
