### ISSUE TITLE
Only one tmux socket is accessible at a time

### ISSUE THREAD

**Issue by oatmealine** [Infinidoge/nix-minecraft#14]
When running 2+ servers, only the most recently started server will have its associated tmux socket file work - the other will just say that there are no sessions:
```
$ doas systemctl restart minecraft-server-dark-firepit

$ doas tmux -S /run/minecraft/gbj.sock attach
no sessions

$ doas systemctl restart minecraft-server-gbj

$ doas tmux -S /run/minecraft/gbj.sock attach
<works perfectly fine>
```

**Comment by Infinidoge** [comment]
Yeah I've been running into this too, and honestly I have no idea why this is the case.
Clearly both servers are still running, so the tmux session for the other server is definitely running.

**Comment by Infinidoge** [comment]
Weirdly, I'm just... not experiencing this problem anymore?
I have no idea what changed, it might have just been caused by a tmux bug that was resolved upstream.
Could you double check in your setup to see if that is the case?
