### ISSUE TITLE
Add a LICENCE file

### ISSUE THREAD

**Issue by imsofi** [Infinidoge/nix-minecraft#2]
Currently this repo is under an "All rights reserved" status where the distribution and use of this repo is disallowed due to copyright. Until this is addressed, technically nobody by law can use this code without your explicit written permission to do so.

I would recommend licensing this project under MIT or ISC, as this is what nixpkgs themselves uses.

**Comment by Infinidoge** [comment]
Oh whoops, good point!

Adding an MIT license now.
