### ISSUE TITLE
Indescriptive error on port overlap assertion

### ISSUE THREAD

**Issue by oatmealine** [Infinidoge/nix-minecraft#28]
There is [an assertion](https://github.com/Infinidoge/nix-minecraft/blob/313cf28a595a3305491b37313d6ac2c76b28d40a/modules/minecraft-servers.nix#L219-L229) set to prevent two servers from using the same port. However, a `message` is not set, producing a confusing error when the assertion is triggered:

```
error: attribute 'message' missing

       at /nix/store/369wr4laqdqzh5brq1g7nfc1pbfh23sn-source/nixos/modules/system/activation/top-level.nix:122:30:

          121|
          122|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                              ^
          123|
(use '--show-trace' to show detailed location information)
```

**Comment by Infinidoge** [comment]
Huh, I thought I would have set a message there, but apparently not!
