### ISSUE TITLE
Enhanchment: Transfer documentation from the module to README.md

### ISSUE THREAD

**Issue by Silverdev2482** [Infinidoge/nix-minecraft#51]
The README says refer to the module for documentation, can the documentation simply be copied over to the README? I would be willing to do that and do some minor touchups.

**Comment by Silverdev2482** [comment]
Should I go ahead and make a pr for this?

**Comment by Silverdev2482** [comment]
Is there a chance a pr for this would get accepted?

**Comment by Infinidoge** [comment]
Sorry for the delay. It's towards the end of the semester, so things have gotten pretty busy for me. A PR to add documentation would be accepted, but as said may take a little while to be reviewed/merged until my schedule clears up.

**Comment by Silverdev2482** [comment]
I'll try to get to doing this in the next week.

**Comment by Silverdev2482** [comment]
Ok, that was a complete lie, I might get to it this week idk.

**Comment by Silverdev2482** [comment]
This will be fixed #59
