### ISSUE TITLE
Fabric 1.20.4 not working

### ISSUE THREAD

**Issue by FlafyDev** [Infinidoge/nix-minecraft#55]
Hey, I tried running a 1.20.4 fabric server and it doesn't seem to be working. I am getting this error:

```
Failed at step CHDIR spawning /nix/store/fxpm0mf2fj696b6b2p3i5qmlrx9gl27v-unit-script-minecraft-server-datapacktests-post-stop/bin/minecraft-server-datapacktests-post-stop
```

It seems this file is owned by root:root, which is why it says it doesn't exist.

Is anyone able to run a 1.20.4 fabric server? or is the issue only for me?

**Comment by Infinidoge** [comment]
Hmm, that's odd. Can you post your server configuration? This seems to be an issue in the service running it somewhere, as opposed to the Minecraft server itself.

**Comment by Infinidoge** [comment]
Since no information has been provided, I'm going ahead and closing this issue.

**Comment by BreakingTV** [comment]
Hey, have the same error
It only appears if I specify the dataDir folder

I already tried letting the software create it by its own and I tried creating it myself, both not doing anything
If I remove the 'DataDir' option, it works perfectly fine

The error:
`minecraft-server-survival.service: Failed at step CHDIR spawning /nix/store/cp8p3wn3m5bxxjf0v2hifapqj7b74lgh-minecraft-server-survival-stop-post/bin/minecraft-server-survival-stop-post: No such file or directory`

**Comment by Infinidoge** [comment]
What `dataDir` did you specify, and where? Notably, the `minecraft` user/group needs to have permission to access that directory, so doing stuff like using a daia directory in your personal `$HOME` won't work.

**Comment by BreakingTV** [comment]
I made a directory at `/mnt/raid/services` named `minecraft`
The `services` folder is owned by my main account
The `minecraft` folder is owned by the Minecraft user/group

That means it could already create the folder (because even if I didnt create it, it would be after a rebuild) and it had permissions on it

**Comment by Infinidoge** [comment]
What were the permissions on `/mnt/raid/services`? If it was missing the global execute permission, then `minecraft` wouldn't be able to see that folder. The folder gets greater by root, so whether or not it gets created isn't a test of whether or not it can see it.

**Comment by Infinidoge** [comment]
What are the permissions on `/mnt`, `/mnt/raid`, and `/mnt/raid/services` respectively?

My guess is either: Other services are run on `root`, and thus don't care, or they use specific systemd options that I'm not aware of that bypass it. (Probably read-write paths or something.)
