### ISSUE TITLE
Feature Request: Using the module without Tmux

### ISSUE THREAD

**Issue by frantisekhanzlikbl** [Infinidoge/nix-minecraft#63]
Hi. First things first, thanks for your (and all the contributors') amazing work on this! I spent far too much time packaging various servers & proxies myself, and this project is going to make my life much easier. :heart:

I'd also love to migrate my ad-hoc solution to the provided module, but I don't really like the fact that it runs the server in a tmux session. I love Tmux as a terminal multiplexer, but using it for services has some really annoying problems that I don't think can be solved in any elegant way:
* Logs don't end up in the system journal—this is probably the biggest one. This means that when something goes wrong and the service crashes, I am left without any information whatsoever unless it ends up in the server logs (which, e.g., startup script failures won't.). It also means I can't process the logs automatically via Loki, fail2ban, and other such tools.
* The server can't be nicely automated from the outside. I really don't want to blindly pipe random keys into tmux and pray that they end up in the command prompt, not mixed with some other rubbish.
* Connecting to the socket remotely is unnecessarily complicated.
* Although not strictly forced by using tmux, I dislike having to run all servers under the same user. Ideally, I'd use systemd's `DynamicUser` for every server. Supporting this with Tmux would be fairly complicated.

A solution that I use currently, which has none of these problems, is to just run the server process directly, controlling it via RCON. It's not perfect, particularly because none of the RCON clients I could find are very nice, but I find it to be a much cleaner approach.

I'd love to add support for this workflow to the provided module, but I'm not sure whether such a PR would be accepted. If so, how do you think it should work? A global toggle? A per-server one? Something else? I'm open to all suggestions.

Thanks in advance!

EDIT: I just noticed #52, which addresses most of these issues. I guess I'll use the fork from there for now, and add support for multiple users after it lands.

**Comment by Infinidoge** [comment]
I'd rather not use tmux either, however unfortunately I haven't really found a good replacement that is less weighty yet. Abduco or similar would be a preferable replacement. The reason why it uses tmux at all is so that the actual console can be accessed, because annoyingly that is impossible to do directly via systemd sockets. (And IMO, rcon is just plain bad. I tried to use it once and stopped immediately because it was so inadequate. I like to actually see what's happening as the server runs lol. Admittedly I do use commands more extensively through the console than the average admin.)

As per that PR, it will hopefully in the future be a configurable option, it just isn't yet. If I get some free time, I might poke at it myself, however being in college unfortunately ties up most of my time.

**Comment by frantisekhanzlikbl** [comment]
Yeah, I feel you. I'm in college myself, and it's nearly impossible to find time for anything. It's true that RCON is pretty bad, but to be fair, you still get *some* amount of feedback, so I've been willing to stick with it for years. I'll see if I find the time to make #52 mergeable, but no promises for now. :-)

**Comment by Infinidoge** [comment]
Personally the biggest problem for me is that I don't get a live console output, only responses to commands, when I rely a lot on the console output. fRCON does seem to be a big improvement, at least.

**Comment by frantisekhanzlikbl** [comment]
Yep. I get what you're saying. I mostly just use `journald -f`, but I'm still very much pro making the behaviour configurable, if only to keep backwards compat. I'll try to make #52 configurable when I find the time and make a PR. Until then, unless you think this isn't really a problem, I'd probably keep this issue open.

**Comment by Infinidoge** [comment]
The issue will definitely stay open. I'm surprised I hadn't made one myself for it before, since this is an issue I've known about and intended to fix for the longest time.

**Comment by frantisekhanzlikbl** [comment]
Alright, I planned to move this forward much sooner, but college was colleging & job jobbing, so I didn't have a single hour of leisure time in the last two months. #67 should be a good step in the right direction, though. :slightly_smiling_face:

**Comment by Infinidoge** [comment]
Thanks for the PR! It's absolutely a step in the right direction, and it uses submodules in a way I hadn't considered using for it, definitely need to use submodules more.

**Comment by Piecuuu** [comment]
I, personally, like the tmux approach to the console, because it's not much different than starting the server manually with `java -jar` and controlling it with a console. What I DO mind is that, the logs do not go in the journal. It's just unintuitive, because if you just quickly wanna check the logs, you could have just opened the journal, instead of tmux/`latest.log`.

**Comment by Infinidoge** [comment]
I very much agree. That and tmux is just really heavy for this kind of thing. Ideally there would be an entirely new tool that is light and only provides the console, while still providing the logs to systemd. Making that kind of tool would take time and effort that I just don't have right now, unfortunately, though if you do find one let me know.

**Comment by Piecuuu** [comment]
> Ideally there would be an entirely new tool that is light and only provides the console, while still providing the logs to systemd.

Lightweight? Maybe GNU Screen, but I don't know if that can integrate with systemd in such a way.

**Comment by Infinidoge** [comment]
Screen hard-codes the socket directory, so it would have to be recompiled :)
