### ISSUE TITLE
Allow the files option to accept directories

### ISSUE THREAD

**Issue by Jamalam360** [Infinidoge/nix-minecraft#73]
Forgive my ignorance if this isn't possible, but it would be nice if the files option could accept directories.

The symlinks option does not work for the config folder since it needs to be writable (this is mentioned in the files option docs). I'd rather not specify every config file individually in the files option 😂

**Comment by Jamalam360** [comment]
For now I'm working around using the function in https://github.com/Infinidoge/nix-minecraft/pull/43/files

**Comment by Misterio77** [comment]
Will be fixed by #116
