### ISSUE TITLE
Errors when starting server

### ISSUE THREAD

**Issue by greysilly7** [Infinidoge/nix-minecraft#79]
Please help me I cant figure it out

code
> {
  pkgs,
  lib,
  ...
}: let
  modpack = pkgs.fetchPackwizModpack {
    url = "https://github.com/Alpaca-Industries/iremia-comeback/raw/1.0.0/pack.toml";
    packHash = "sha256-i+W0WA/eH/tNmYzguP2/v/rJb1LUnCV4WmMO9FpjcdI=";
  };
  mcVersion = modpack.manifest.versions.minecraft;
  fabricVersion = modpack.manifest.versions.fabric;
  serverVersion = lib.replaceStrings ["."] ["_"] "fabric-${mcVersion}";
in {
  services.minecraft-servers.servers.iremia = {
    enable = true;
    autoStart = true;
    package = pkgs.fabricServers.${serverVersion}.override {loaderVersion = fabricVersion;};

    serverProperties = {
      server-port = 18611;
      /*
      difficulty = 3;
      gamemode = 1;
      max-players = 5;
      motd = "IREMIA!";
      white-list = false;
      */
      enable-rcon = true;
      "rcon.password" = "password";
    };

    symlinks = {
      "mods" = "${modpack}/mods";
      # "config" = "${modpack}/config";
    };
  };
}

errors:
> Jun 30 15:28:01 greyserver wqnygk7snd6hzyswf2aigwv0pi6yazpn-minecraft-start-iremia[192689]: error connecting to /run/minecraft/iremia.sock (Permission denied)
Jun 30 15:28:01 greyserver wqnygk7snd6hzyswf2aigwv0pi6yazpn-minecraft-start-iremia[192690]: error connecting to /run/minecraft/iremia.sock (Permission denied)
Jun 30 15:28:01 greyserver systemd[1]: minecraft-server-iremia.service: Control process exited, code=exited, status=1/FAILURE`

> × minecraft-server-iremia.service - Minecraft Server iremia
     Loaded: loaded (/etc/systemd/system/minecraft-server-iremia.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-06-30 15:28:02 EDT; 5min ago
    Process: 192667 ExecStartPre=/nix/store/zmf8qdrgvavixb95gfdf27957cai4560-unit-script-minecraft-server-iremia-pre-start/bin/minecraft-server-iremia-pre-start (code=exited, status=0/SUCC>
    Process: 192682 ExecStart=/nix/store/wqnygk7snd6hzyswf2aigwv0pi6yazpn-minecraft-start-iremia (code=exited, status=1/FAILURE)
    Process: 192692 ExecStopPost=/nix/store/bsw2fzdnqr6ihx1w96arv9f9252nj5qb-unit-script-minecraft-server-iremia-post-stop/bin/minecraft-server-iremia-post-stop (code=exited, status=0/SUCC>
         IP: 0B in, 0B out
        CPU: 89ms

> Jun 30 15:28:02 greyserver systemd[1]: minecraft-server-iremia.service: Scheduled restart job, restart counter is at 5.
Jun 30 15:28:02 greyserver systemd[1]: minecraft-server-iremia.service: Start request repeated too quickly.
Jun 30 15:28:02 greyserver systemd[1]: minecraft-server-iremia.service: Failed with result 'exit-code'.
Jun 30 15:28:02 greyserver systemd[1]: Failed to start Minecraft Server iremia.`

**Comment by bluelinden** [comment]
i fixed this on my end by stopping `minecraft-server-[NAME].service` with `[sudo] systemctl stop [servicename]`, deleting `/run/minecraft/[NAME].sock` and starting `minecraft-server-[NAME].service` again.

**Comment by Infinidoge** [comment]
Strange. What are the permissions on `/run/minecraft`?

**Comment by greysilly7** [comment]
It was just the server crashing, trying to figure out how to change the java version now

**Comment by mechan1sm** [comment]
I get the same error related to "JAVA_21 compability level could not be set" when using Fabric 1.21 with following mods:
- fabric-api-0.100.4+1.21.jar
- fabric-carpet-1.21-1.4.147+v240613.jar
- carpet-tis-addition-mc1.21-v1.60.1.jar (the one that causes the crash)
