### ISSUE TITLE
Discord MC Chat crashes on nix-minecraft, fabric jar is the suspect cause.

### ISSUE THREAD

**Issue by Silverdev2482** [Infinidoge/nix-minecraft#87]
Here is a server where the files have been pulled down from the nix store, there are two start up scripts identical in everything except the fabric jar they use. [1.20.4.tar.zstd](https://drive.google.com/file/d/1-2YcNV_dCASQZQH4uL4wzCo9SPDfl_8d/view?usp=sharing) It should contain the logs but they are available [here](https://github.com/user-attachments/files/16432961/2024-07-30-1.log)

I have talked with the developer on his [discord](https://discord.gg/kbXkV6k2XU). The conversation started [here](https://discord.com/channels/1023044700346777611/1258412153875206179/1267661591961407621), and has been mostly uninterrupted

**Comment by Xujiayao** [comment]
This is the same issue as #79. #80 should solve the problem. ASM 9.2 does not support Java 21.
