### ISSUE TITLE
[Feature Request] Configure nginx

### ISSUE THREAD

**Issue by lomenzel** [Infinidoge/nix-minecraft#97]
it would be nice to have the option to set server.<name>.hostName = "minecraftserver1.example.com" and it would automatically configure nginx to proxypass that server.

**Comment by lomenzel** [comment]
Yes proxy pass does not work with Minecraft servers, but I guess it's possible to use nginx to map Minecraft servers to Subdomains. https://github.com/vollborn/minecraft-nginx-reverse-proxy/blob/main/src/nginx.conf ← that seems to somehow do it. In my opinion Domains and Subdomains are much more user-friendly than dealing with port numbers to connect

**Comment by Infinidoge** [comment]
You can use SRV records instead of ports to accomplish this.

Specifically, A SRV record of `_minecraft._tcp.subdomain` with the port number, targeting a DNS record with your IP.

For example, I have `_minecraft._tcp.temp.mc` with port `25565` targeting `tmp.mc.inx.moe` which points to my IP.

**Comment by Infinidoge** [comment]
Setting up an Nginx server in this way is out of scope for the module, as that deals with hosting an outside proxy and not a server itself. If you need further help setting up SRV records, please open a discussion post.
